### ISSUE TITLE
Correcciones y sugerenicias

### ISSUE THREAD

**Issue by flbulgarelli** [ariel-/tp-dds-qmp#1]
¡Buenas!

Te dejo nuestros comentarios:

1. El primer método de esta clase https://github.com/ariel-/tp-dds-qmp/blob/387f6b2b3c6fa248d2f96573ae4b6915602cc3e2/src/main/java/domain/servicios/clima/accuweather/AccuWeatherAPI.java#L8-L27 se comporta como un mock. Por tanto, `AccuWeatherAPI` debería ser una interfaz (externa) y sus implementaciones (mockeadas) deberían ser parte del código de prueba (en `src/test/java`), ya sea implementado como una clase común o usando mockito
2. La estructura de tus interfaces de suscriptor clima están bien :+1: 
3. Tu ServicioClimaAccuWeather está muy bien encarado. Mi única crítica es respecto a la implementación del disparo de las notificaciones es que sólo se lanzarán como consecuencia de llamar a `estadoClimatico` (que no parece tener un efecto evidente). Probablemente te convenga tener un método publico en esta implementación a sólo fin de realizar el chequeo de si cambió el estado del clima y desparar las alertas. Luego, ese método podrías llamarlo periódicamente. Quizás la implementación termine siendo muy similar a `estadoClimatico`, pero tendrá un nombre mucho más evidente. 

Por último, no termino ver reflejado ésto: 

> Como usuarie de QueMePongo, quiero poder conocer cuáles son las últimas alertas meteorológicas publicadas en el sistema para estar informado (pudiendo verlas, por ejemplo, al entrar en quemepongo.com)

en ningún lugar veo esto implementado. ¿Puede ser?

¡Saludos!

**Comment by ariel-** [comment]
> Por último, no termino ver reflejado ésto:

>>    Como usuarie de QueMePongo, quiero poder conocer cuáles son las últimas alertas meteorológicas publicadas en el sistema para estar informado (pudiendo verlas, por ejemplo, al entrar en quemepongo.com)

> en ningún lugar veo esto implementado. ¿Puede ser?

Puede ser, yo lo pensé, al ser _user story_, que esto significaba poder obtener las alertas. Es básicamente la función del servicio de clima. Está bien pensarlo así? Es decir, en algún momento la capa de presentación (quemepongo.com) va a solicitar al servicio climático un estado, y de alli obtendrá las alertas actuales.

En cuanto a los otros puntos, gracias por el feedback, me parecía raro que fuera la única que tenia como una especie de implementación mock, en lugar de por ejemplo `MailSender` que era solamente una interfaz.

**Comment by flbulgarelli** [comment]
> Puede ser, yo lo pensé, al ser user story, que esto significaba poder obtener las alertas. Es básicamente la función del servicio de clima. Está bien pensarlo así? Es decir, en algún momento la capa de presentación (quemepongo.com) va a solicitar al servicio climático un estado, y de alli obtendrá las alertas actuales.

¡Hola! Sí, en parte eso lo resuelve el servicio de clima, pero acá la idea de poder conocer _las últimas_ alertes _publicadas_ a lo que apunta es a que de alguna forma puedas gestionar esas publicaciones de las alertes más recientes, quizás simplemente teniendo un repositorio de alertas, que te pueda decir cuales son las (por ejemplo) últimas 10 que ocurrieron. Y cada vez que se produzca una alerta, guardarla en ese repositorio.
